[book]
authors = ["The Kubebuilder Maintainers"]
multilingual = true
src = "src"
title = "Kubebuilder 指南"

[preprocessor.gettext]
after = ["links"]

[build]
extra-watch-dirs = ["translation"]

[output.html]
curly-quotes = true
additional-css = ["theme/css/markers.css", "theme/css/custom.css", "theme/css/version-dropdown.css", "theme/css/global-banner.css"]
additional-js = ["theme/js/inject.js"]
git-repository-url = "https://github.com/LJTian/kubebuilder-cn"
edit-url-template = "https://github.com/LJTian/kubebuilder-cn/edit/master/docs/book/{path}"

[preprocessor.literatego]
command = "./litgo.sh"

[preprocessor.markerdocs]
command = "./markerdocs.sh"

[context.environment]
  environment = { GO_VERSION = "1.23" }

[context.deploy-preview.environment]
  environment = { GO_VERSION = "1.23" }

