[book]
authors = ["The Kubebuilder Maintainers"]
multilingual = false
src = "src_zh"
title = "The Kubebuilder Book(汉化)"

[output.html]
curly-quotes = true
additional-css = ["theme/css/markers.css", "theme/css/custom.css", "theme/css/version-dropdown.css"]
git-repository-url = "https://github.com/LJTian/kubebuilder-cn"
edit-url-template = "https://github.com/LJTian/kubebuilder-cn/edit/master/docs/book/{path}"

[preprocessor.literatego]
command = "./litgo.sh"

[preprocessor.markerdocs]
command = "./markerdocs.sh"

[context.environment]
  environment = { GO_VERSION = "1.21" }

[context.deploy-preview.environment]
  environment = { GO_VERSION = "1.21" }

